---

- name: APPLY ACL
  hosts: routers
  gather_facts: false
  connection: network_cli
  become: yes
  become_method: enable


  tasks:
    - name: Apply ACL to Interface
      cisco.ios.ios_acl_interfaces:
        config:
        - name: vlan 3
          access_groups:
          - afi: ipv4
            acls:
            - name: security_acl
              direction: in