---

- name: CONFIGURE ACL
  hosts: routers
  gather_facts: false
  connection: network_cli
  become: yes
  become_method: enable
  
  tasks:
        
    - name: Configure ACL Router
      cisco.ios.ios_acls:
        state: replaced
        config:
        - afi: ipv4
          acls:
          - name: security_acl
            acl_type: extended
            aces:           

            - grant: permit
              sequence: 10
              protocol_options:
                ip: true
              source:
                any: true
              destination:
                host: 192.168.2.1
                  
            - grant: deny
              sequence: 11
              protocol_options:
                tcp:
                  ack: true
              source:
                any: true
              destination:
                address: 192.168.2.0
                wildcard_bits: 0.0.0.255
                port_protocol:
                  eq: telnet

            - grant: deny
              sequence: 12
              protocol_options:
                tcp:
                  ack: true          
              source:
                any: true
              destination:
                address: 192.168.2.0
                wildcard_bits: 0.0.0.255
                port_protocol:
                  eq: ftp
      
            - grant: deny
              sequence: 24
              protocol_options:
                ip: true              
              source:
                any: true
              destination:
                address: 192.168.2.0
                wildcard_bits: 0.0.0.255            
              enable_fragments: true

            - grant: deny
              sequence: 25
              source:
                any: true
              destination:
                address: 192.168.2.0
                wildcard_bits: 0.0.0.255            
              protocol_options:
                icmp: 
                  administratively_prohibited: true  
                  
            - grant: permit
              sequence: 40
              protocol_options:
                tcp:
                  syn: true
              source:
                host: 192.168.180.189
              destination:
                host: 192.168.180.2
                port_protocol:
                  eq: 22
                  
            - grant: permit
              sequence: 41
              protocol_options:
                tcp:
                  syn: true
              source:
                host: 192.168.180.189
              destination:
                address: 192.168.2.0
                wildcard_bits: 0.0.0.255            
                port_protocol:
                  eq: 22
                  
            - grant: permit
              sequence: 42
              protocol_options:
                tcp:
                  syn: true
              source:
                any: true
              destination:
                address: 192.168.2.0
                wildcard_bits: 0.0.0.255            
                port_protocol:
                  eq: 443
