---
- name: Configure firewalld
  hosts: linux
  become: true
  
  tasks:
  - name: Install firewalld
    ansible.builtin.apt:
       name: firewalld
       state: latest
       
  - name: Start service 
    service:
       name: firewalld
       state: started
