---
- name: Implementing security measures for linux server.
  hosts: linux
  become: true
  
  tasks:
  - name: Install Firewalld.
    ansible.builtin.apt:
       name: firewalld
       state: latest
       
  - name: Start Firewalld.
    ansible.builtin.service:  
       name: firewalld
       state: started
       
  - name: Firewalld - Enable https for Zone public.
    ansible.posix.firewalld:
        zone: public
        service: "https"
        permanent: true
        state: enabled

       
  - name: Firewalld - Disable SSH for Zone public.
    ansible.posix.firewalld:
        zone: public
        service: ssh
        permanent: true
        state: disabled
        
  - name: Firewalld - Enable internal services only for the Ansible Security Tower.
    ansible.posix.firewalld:
        zone: internal
        source: 192.168.180.159
        permanent: true
        state: enabled
        
  - name: Restart Firewalld.
    ansible.builtin.service:
        name: firewalld
        state: restarted
        
  - name: sshd - Disable SSH password authentication.
    ansible.builtin.lineinfile:
        dest: /etc/ssh/sshd_config 
        regexp: '^(#\s*)?PasswordAuthentication '
        line: 'PasswordAuthentication no'
            
  - name: Restart sshd.
    ansible.builtin.service:  
       name: sshd
       state: restarted