---
- name: Playbook for restarting apache2 webserver
  hosts: linux
  become: true
  gather_facts: false
  
  tasks:
  - name: Restart apache2
    ansible.builtin.service:
       name: apache2
       state: restarted
